/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsTeamAdminRouteImport } from './routes/teams/$team.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamAdminRoute = TeamsTeamAdminRouteImport.update({
  id: '/teams/$team/admin',
  path: '/teams/$team/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/teams/$team/admin': typeof TeamsTeamAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/teams/$team/admin': typeof TeamsTeamAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/teams/$team/admin': typeof TeamsTeamAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/teams/$team/admin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/teams/$team/admin'
  id: '__root__' | '/' | '/teams/$team/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TeamsTeamAdminRoute: typeof TeamsTeamAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$team/admin': {
      id: '/teams/$team/admin'
      path: '/teams/$team/admin'
      fullPath: '/teams/$team/admin'
      preLoaderRoute: typeof TeamsTeamAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TeamsTeamAdminRoute: TeamsTeamAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
